ARG ALPINE_VERSION=3.21
ARG GO_VERSION=1.23.5

FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION}

ARG USERNAME=appuser
ARG GROUNAME=appgroup
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

RUN apk add --no-cache git sudo openssh-client zsh curl openssl \
    && addgroup -g ${USER_GID} ${GROUNAME} \
    && adduser -u ${USER_UID} -G ${GROUNAME} -s /bin/zsh -D ${USERNAME}

RUN go install github.com/cweill/gotests/gotests@latest \
    && go install -v github.com/fatih/gomodifytags@latest \
    && go install -v github.com/josharian/impl@latest \
    && go install -v github.com/go-delve/delve/cmd/dlv@latest \
    && go install -v honnef.co/go/tools/cmd/staticcheck@latest \
    && go install -v golang.org/x/tools/gopls@latest \
    && go install -v golang.org/x/tools/cmd/goimports@latest

USER ${USERNAME}
WORKDIR /home/${USERNAME}
